"""
Test Script for Phase 1: PDF Generation & Export

Tests the core functionality:
1. PDF generation from Markdown
2. DOCX export
3. Markdown export
4. LaTeX export
5. End-to-end document processing
"""

import asyncio
import sys
from pathlib import Path

# Add backend to path
sys.path.insert(0, str(Path(__file__).parent))

from app.services.pdf_generator import generate_pdf_from_markdown
from app.services.docx_exporter import export_markdown_to_docx


async def test_pdf_generation():
    """Test PDF generation with math expressions"""
    print("\n" + "=" * 60)
    print("TEST 1: PDF Generation")
    print("=" * 60)
    
    sample_markdown = """
# Calculus Notes

## Introduction to Derivatives

The derivative of a function $f(x)$ is defined as:

$$
f'(x) = \\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}
$$

### Common Derivatives

- Polynomial: $\\frac{d}{dx}(x^n) = nx^{n-1}$
- Exponential: $\\frac{d}{dx}(e^x) = e^x$
- Trigonometric: $\\frac{d}{dx}(\\sin x) = \\cos x$

## Example Problem

Find the derivative of $f(x) = x^2 + 3x + 5$:

$$
f'(x) = 2x + 3
$$

**Code Example:**
```python
def derivative(x):
    return 2*x + 3
```

> Remember: Practice makes perfect!

---

*Generated by File Data Extractor*
    """
    
    metadata = {
        "title": "Calculus Derivatives",
        "author": "Test User",
        "date": "2026-02-04"
    }
    
    try:
        # Test modern style
        print("\n📄 Generating PDF (modern style)...")
        pdf_bytes = await generate_pdf_from_markdown(sample_markdown, metadata, style="modern")
        
        # Save test output
        output_path = Path(__file__).parent / "temp" / "test_modern.pdf"
        output_path.parent.mkdir(exist_ok=True)
        output_path.write_bytes(pdf_bytes)
        print(f"✅ PDF generated successfully: {output_path}")
        print(f"   Size: {len(pdf_bytes):,} bytes")
        
        # Test academic style
        print("\n📄 Generating PDF (academic style)...")
        pdf_bytes_academic = await generate_pdf_from_markdown(sample_markdown, metadata, style="academic")
        output_path_academic = Path(__file__).parent / "temp" / "test_academic.pdf"
        output_path_academic.write_bytes(pdf_bytes_academic)
        print(f"✅ PDF generated successfully: {output_path_academic}")
        print(f"   Size: {len(pdf_bytes_academic):,} bytes")
        
    except Exception as e:
        print(f"❌ PDF generation failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return False
    
    return True


async def test_docx_export():
    """Test DOCX export"""
    print("\n" + "=" * 60)
    print("TEST 2: DOCX Export")
    print("=" * 60)
    
    sample_markdown = """
# Research Paper

## Abstract

This document demonstrates **DOCX export** functionality.

## Key Points

- Point 1: *Important concept*
- Point 2: Mathematical expression $E = mc^2$
- Point 3: Code snippet

### Code Example

```python
print("Hello, World!")
```

## Conclusion

The export works!
    """
    
    metadata = {
        "title": "Research Paper",
        "author": "Test User"
    }
    
    try:
        print("\n📝 Generating DOCX...")
        docx_bytes = await export_markdown_to_docx(sample_markdown, metadata)
        
        # Save test output
        output_path = Path(__file__).parent / "temp" / "test_export.docx"
        output_path.parent.mkdir(exist_ok=True)
        output_path.write_bytes(docx_bytes)
        print(f"✅ DOCX generated successfully: {output_path}")
        print(f"   Size: {len(docx_bytes):,} bytes")
        
    except Exception as e:
        print(f"❌ DOCX export failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return False
    
    return True


async def test_math_rendering():
    """Test complex math rendering"""
    print("\n" + "=" * 60)
    print("TEST 3: Complex Math Rendering")
    print("=" * 60)
    
    complex_math = """
# Advanced Mathematics

## Fourier Transform

$$
\\hat{f}(\\xi) = \\int_{-\\infty}^{\\infty} f(x) e^{-2\\pi i x \\xi} dx
$$

## Maxwell's Equations

1. Gauss's law: $\\nabla \\cdot \\mathbf{E} = \\frac{\\rho}{\\epsilon_0}$

2. Gauss's law for magnetism: $\\nabla \\cdot \\mathbf{B} = 0$

3. Faraday's law: $\\nabla \\times \\mathbf{E} = -\\frac{\\partial \\mathbf{B}}{\\partial t}$

4. Ampère's law: $\\nabla \\times \\mathbf{B} = \\mu_0\\mathbf{J} + \\mu_0\\epsilon_0\\frac{\\partial \\mathbf{E}}{\\partial t}$

## Schrödinger Equation

$$
i\\hbar\\frac{\\partial}{\\partial t}\\Psi(\\mathbf{r},t) = \\hat{H}\\Psi(\\mathbf{r},t)
$$
    """
    
    metadata = {
        "title": "Advanced Mathematics",
        "author": "Test User"
    }
    
    try:
        print("\n📐 Generating PDF with complex math...")
        pdf_bytes = await generate_pdf_from_markdown(complex_math, metadata)
        
        output_path = Path(__file__).parent / "temp" / "test_complex_math.pdf"
        output_path.write_bytes(pdf_bytes)
        print(f"✅ Complex math PDF generated: {output_path}")
        print(f"   Size: {len(pdf_bytes):,} bytes")
        
    except Exception as e:
        print(f"❌ Complex math rendering failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return False
    
    return True


async def run_all_tests():
    """Run all Phase 1 tests"""
    print("\n" + "=" * 60)
    print("🚀 PHASE 1 TEST SUITE")
    print("   Testing PDF Generation & Export Features")
    print("=" * 60)
    
    results = []
    
    # Test 1: PDF Generation
    results.append(("PDF Generation", await test_pdf_generation()))
    
    # Test 2: DOCX Export
    results.append(("DOCX Export", await test_docx_export()))
    
    # Test 3: Complex Math
    results.append(("Complex Math Rendering", await test_math_rendering()))
    
    # Print summary
    print("\n" + "=" * 60)
    print("📊 TEST SUMMARY")
    print("=" * 60)
    
    passed = sum(1 for _, result in results if result)
    total = len(results)
    
    for test_name, result in results:
        status = "✅ PASS" if result else "❌ FAIL"
        print(f"{status}: {test_name}")
    
    print(f"\nTotal: {passed}/{total} tests passed")
    print("=" * 60)
    
    if passed == total:
        print("\n🎉 All tests passed! Phase 1 core features are working.")
        print("\n📁 Test outputs saved to: backend/temp/")
        return True
    else:
        print(f"\n⚠️  {total - passed} test(s) failed. Please check errors above.")
        return False


if __name__ == "__main__":
    print("\n" + "=" * 60)
    print("File Data Extractor - Phase 1 Test Suite")
    print("=" * 60)
    
    # Check if dependencies are installed
    try:
        import markdown
        import weasyprint
        from docx import Document
        print("✅ All dependencies are installed")
    except ImportError as e:
        print(f"\n❌ Missing dependency: {e}")
        print("\n📦 Please install dependencies first:")
        print("   cd backend")
        print("   pip install -r requirements.txt")
        print("\nNote: WeasyPrint requires additional system dependencies:")
        print("   - Windows: GTK3 runtime (https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer)")
        print("   - Linux: sudo apt-get install libpango-1.0-0 libpangoft2-1.0-0")
        print("   - macOS: brew install pango")
        sys.exit(1)
    
    # Run tests
    success = asyncio.run(run_all_tests())
    sys.exit(0 if success else 1)
